# Generated by Django 4.0.5 on 2022-10-12 12:15

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountLogin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_num', models.CharField(default='', max_length=30, verbose_name='Account_number')),
                ('account_password', models.CharField(default='', max_length=20, verbose_name='Account_password')),
                ('account_status', models.SmallIntegerField(blank=True, choices=[(1, 'OK'), (2, 'BAD'), (0, 'unknown')], default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CompanyType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('com_name', models.CharField(max_length=20, unique=True)),
                ('com_desc', models.CharField(blank=True, max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ContractType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cont_name', models.CharField(max_length=20, unique=True)),
                ('cont_desc', models.CharField(blank=True, max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count_name', models.CharField(max_length=20)),
                ('count_ware', models.CharField(max_length=32, null=True, unique=True)),
                ('count_desc', models.CharField(max_length=32, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dep_name', models.CharField(max_length=20)),
                ('mission', models.CharField(max_length=20, unique=True)),
                ('mission_desc', models.CharField(max_length=32, null=True)),
                ('warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='msm.country')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workid', models.CharField(blank=True, max_length=32, null=True, unique=True)),
                ('first_name', models.CharField(default='', max_length=50, verbose_name='First name')),
                ('second_name', models.CharField(default='', max_length=50, verbose_name='Second name')),
                ('birthday', models.DateField(null=True, verbose_name='Birthday')),
                ('gender', models.SmallIntegerField(blank=True, choices=[(1, 'male'), (2, 'female'), (0, 'unknown')], default=0, null=True)),
                ('address', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Address')),
                ('join_time', models.DateField(null=True, verbose_name='Join time')),
                ('end_time', models.DateField(null=True, verbose_name='End time')),
                ('mobile', models.CharField(blank=True, max_length=15, null=True, verbose_name='Phone number')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='Creat time')),
                ('data_status', models.BooleanField(default=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='msm.companytype')),
                ('contract_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='msm.contracttype', verbose_name='Level')),
                ('dep_mission', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='Department_Mission', to='msm.department')),
            ],
            options={
                'ordering': ['-join_time'],
            },
        ),
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_status', models.SmallIntegerField(blank=True, choices=[(1, 'OK'), (2, 'BAD'), (0, 'unknown')], default=0, null=True)),
                ('account_num', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='msm.accountlogin')),
                ('work_num', models.ForeignKey(blank=True, default='123456', max_length=50, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='msm.userprofile', to_field='workid', verbose_name='WorkID')),
            ],
        ),
        migrations.CreateModel(
            name='SubMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fathermenu', models.CharField(blank=True, max_length=32, null=True)),
                ('menuid', models.CharField(blank=True, max_length=32, null=True)),
                ('router', models.CharField(blank=True, max_length=32, null=True)),
                ('menu_status', models.BooleanField(blank=True, default=True, null=True)),
                ('title_group', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='msm.department')),
            ],
            options={
                'ordering': ['menuid'],
            },
        ),
        migrations.CreateModel(
            name='ExternalWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ew_name', models.CharField(blank=True, max_length=50, null=True)),
                ('ex_start_time', models.CharField(blank=True, max_length=50, null=True)),
                ('ex_end_time', models.CharField(blank=True, max_length=50, null=True)),
                ('ex_long_time', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('ex_work_reason', models.CharField(blank=True, max_length=100, null=True)),
                ('ex_work_date', models.DateField(blank=True, default=datetime.date(2022, 10, 12), null=True)),
                ('ex_work_way', models.CharField(blank=True, max_length=32, null=True)),
                ('ex_data_status', models.BooleanField(blank=True, default=True, null=True)),
                ('ew_workid', models.ForeignKey(blank=True, default='123456', max_length=50, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='msm.userprofile', to_field='workid', verbose_name='WorkID')),
                ('ex_group', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='group', to='msm.department')),
            ],
            options={
                'ordering': ['ex_long_time'],
            },
        ),
        migrations.CreateModel(
            name='CheckinTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_today', models.DateField(blank=True, default=datetime.date(2022, 10, 12), null=True)),
                ('tags', models.SmallIntegerField(blank=True, default=0, null=True)),
                ('arr_time', models.CharField(blank=True, max_length=32, null=True)),
                ('lea_time', models.CharField(blank=True, max_length=32, null=True)),
                ('arr_photo', models.ImageField(blank=True, default='', null=True, upload_to='photos', verbose_name='签到')),
                ('lea_photo', models.ImageField(blank=True, default='', null=True, upload_to='photos', verbose_name='离开')),
                ('supp_status', models.SmallIntegerField(blank=True, choices=[(1, 'arrive'), (2, 'leave'), (0, 'No')], default=0, null=True)),
                ('sign_status', models.BooleanField(blank=True, default=False, null=True)),
                ('group', models.ForeignKey(blank=True, default='Not defound', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='msm.department', verbose_name='Depart')),
                ('workid', models.ForeignKey(blank=True, default='123456', max_length=50, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='msm.userprofile', to_field='workid', verbose_name='WorkID')),
            ],
            options={
                'ordering': ['arr_time'],
            },
        ),
        migrations.CreateModel(
            name='ChangeGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.CharField(blank=True, max_length=32, null=True)),
                ('finish_time', models.CharField(blank=True, max_length=32, null=True)),
                ('change_status', models.BooleanField(blank=True, default=True, null=True)),
                ('date_today', models.DateField(blank=True, default=datetime.date(2022, 10, 12), null=True)),
                ('data_status', models.BooleanField(blank=True, default=True, null=True)),
                ('cg_workid', models.ForeignKey(blank=True, default='123456', max_length=50, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='msm.userprofile', to_field='workid', verbose_name='WorkID')),
                ('finish_group', models.ForeignKey(default=2, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='end_group', to='msm.department')),
                ('start_group', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='begin_group', to='msm.department')),
            ],
            options={
                'ordering': ['change_status'],
            },
        ),
    ]
