# Generated by Django 4.0.5 on 2022-10-13 07:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changegroup',
            name='date_today',
            field=models.DateField(blank=True, default=datetime.date(2022, 10, 13), null=True),
        ),
        migrations.AlterField(
            model_name='checkintable',
            name='date_today',
            field=models.DateField(blank=True, default=datetime.date(2022, 10, 13), null=True),
        ),
        migrations.AlterField(
            model_name='externalwork',
            name='ex_work_date',
            field=models.DateField(blank=True, default=datetime.date(2022, 10, 13), null=True),
        ),
    ]
