# Generated by Django 4.0.5 on 2022-10-18 07:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msm', '0003_alter_changegroup_date_today_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companytype',
            name='is_active',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name='changegroup',
            name='date_today',
            field=models.DateField(blank=True, default=datetime.date(2022, 10, 18), null=True),
        ),
        migrations.AlterField(
            model_name='checkintable',
            name='date_today',
            field=models.DateField(blank=True, default=datetime.date(2022, 10, 18), null=True),
        ),
        migrations.AlterField(
            model_name='externalwork',
            name='ex_work_date',
            field=models.DateField(blank=True, default=datetime.date(2022, 10, 18), null=True),
        ),
    ]
