# Generated by Django 4.0.5 on 2022-10-19 09:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msm', '0004_companytype_is_active_alter_changegroup_date_today_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkintable',
            name='sign_status',
        ),
        migrations.AddField(
            model_name='checkintable',
            name='data_status',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name='changegroup',
            name='date_today',
            field=models.DateField(blank=True, default=datetime.date(2022, 10, 19), null=True),
        ),
        migrations.AlterField(
            model_name='checkintable',
            name='date_today',
            field=models.DateField(blank=True, default=datetime.date(2022, 10, 19), null=True),
        ),
        migrations.AlterField(
            model_name='externalwork',
            name='ex_work_date',
            field=models.DateField(blank=True, default=datetime.date(2022, 10, 19), null=True),
        ),
    ]
