# Generated by Django 4.0.5 on 2022-10-20 07:47

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('msm', '0005_remove_checkintable_sign_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changegroup',
            name='date_today',
            field=models.DateField(blank=True, default=datetime.date(2022, 10, 20), null=True),
        ),
        migrations.AlterField(
            model_name='checkintable',
            name='date_today',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='externalwork',
            name='ex_work_date',
            field=models.DateField(blank=True, default=datetime.date(2022, 10, 20), null=True),
        ),
    ]
