# Generated by Django 4.0.5 on 2022-10-13 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0002_remove_userinfo_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menu',
            options={'ordering': ['weight']},
        ),
    ]
